### PR TITLE
fixes #19 which was caused by #15 changing data type thats passed into check_ips

### LINKED ISSUE #19: Resolve issue with plugin version 1.2.0
Encountered an issue with version 1.2.0 of this plugin:

Check results with 1.2.0:

```
$ruby ./check-dns-1-2-0.rb -s 8.8.8.8 -d google.com -r 74.125.202.100
Check failed to run: undefined method `answer' for #<Array:0x895b73c>, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:215:in `check_ips'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:185:in `block in check_results'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:165:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:165:in `check_results'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:229:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

Output of 1.1.0 version of this plugin:

```
$ruby ./check-dns-1-1-0.rb -s 8.8.8.8 -d google.com -r 74.125.202.100
DNS OK: Resolved UNCHECKED google.com A included 74.125.202.100
```

Some debug information:

```
--/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/ipv6.rb:93: `cannot interpret as IPv4 address: "MY_HOSTNAME"' (ArgumentError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resolver.rb:513:in `set_config_nameserver'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resolver.rb:458:in `block in initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resolver.rb:453:in `each'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/resolver.rb:453:in `initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:126:in `new'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:126:in `resolve_domain'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dns-1.2.0/bin/check-dns.rb:228:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.0/lib/dnsruby/ipv6.rb:93:          raise ArgumentError.new("not numeric IPv6 address: " + arg)
```

I haven't dig into diff between versions 1.1.0 and 1.2.0, though.
My environment:

Ruby version:

```
ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
```

Gem version:

```
gem --version
2.6.6
```
OS: Ubuntu 12.04 i386 Kernel: 3.2.0-55-virtual

This host is pretty old and support term for 12.04 have already ended. So, if this issue is related to an outdated environment, please, advise and close this issue.

Thanks!

### PR DESCRIPTION
**Pull request by majormoses**
## Pull Request Checklist

#19 which was caused by #15 

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### Purpose
Fix bug

### CODE REVIEW

**Comment by majormoses** [comment]
the data type passed into `check_ips` changed from `Dnsruby::Message` to an array with a size of 1 regardless of how many ips are used. We should look to change this back but in the mean time I wanted to quickly hotfix it worked around it by selecting the first elem in array.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-dns/versions/1.2.1
